#262 main nav css update
OnroerendErfgoed/pyoes pull request #263
Opened 2023-02-21 14:24 UTC by yannickkuypers

Issue #262 

Voor https://github.com/OnroerendErfgoed/beeldbank/issues/2309

2023-02-22 08:33 UTC, roefem requested changes

2023-02-22 08:33 UTC, roefem commented on pyoes/templates/pyoes/header.jinja2
> +        <li{% if id==active_main_nav %} class="active" {% endif %}{% if class %} class="{{ class }}" {% endif %}>
`        <li class="{{ 'active'  if id == active_main_nav else '' }} {{class or ''}}">`

2023-02-23 12:29 UTC, roefem approved these changes

2023-02-23 19:41 UTC, JonasGe requested changes

2023-02-23 19:41 UTC, JonasGe commented on pyoes/templates/pyoes/header.jinja2
> +        </li>
Die indentation is hier niet goed, dat moet ook verder ingesprongen staan.

2023-02-24 15:35 UTC, JonasGe approved these changes

2023-02-27 07:45 UTC, merged