Feature/282 opkuis jinjas vlaanderen header
OnroerendErfgoed/pyoes pull request #284
Opened 2023-12-03 15:53 UTC by cedrikv

Met extra test pagina voor burgerprofiel header&footer:
![image](https://github.com/OnroerendErfgoed/pyoes/assets/1849458/98b4f09d-e304-4e1b-bd8d-5abda89c442c)

2023-12-04 11:41 UTC, JonasGe approved these changes
Ik weet wel niet of het de bedoeling is dat er al ID's ingevuld zijn in de burgerprofiel.jinja2?

2023-12-04 12:15 UTC, roefem commented
kan de ruimte die die header en footer innemen al gereserveerd worden? voorah header zou nice zijn

2023-12-12 13:00 UTC, roefem requested changes
change request voor de header placeholder

2023-12-12 13:38 UTC, cedrikv commented
just, die was ik idd vergeten. met alle adresregisterproblemen :/

2023-12-13 13:04 UTC, roefem approved these changes

2023-12-13 13:04 UTC, roefem approved these changes

2023-12-14 08:02 UTC, merged