Feature/306 ghactions backend upgrade
OnroerendErfgoed/pyoes pull request #307
Opened 2024-09-03 08:33 UTC by JonasGe

Fixes #306

2024-09-04 08:46 UTC, cedrikv commented
moet de MANIFEST.in blijven staan?

2024-09-10 07:50 UTC, vancamti requested changes
Bij voorkeur ook ineens pre-commit toevoegen en alle python files deftig formatten en linten

2024-09-10 07:50 UTC, vancamti commented on pyproject.toml
> +[project.entry-points."paste.app_factory"]
moeten die quotes hier staan ? op die "paste.app_factory"

2024-09-10 07:50 UTC, vancamti commented on pyproject.toml
> +[project.entry-points."pyramid.scaffold"]
moeten die quotes hier staan ?

2024-09-10 11:55 UTC, vancamti approved these changes

2024-09-11 07:06 UTC, merged